"""Collection of common util functions and dictionaries"""

"""Dictionary of potential words (values) that indicate content warnings and the type of warning (key)"""
content_warnings = {
    "politics": [
        "politics",
        "political",
        "prime minister",
        "trump",
        "bipartisan",
        "government",
        "taoiseach",
        "governor",
        "mayor",
        "referendum",
    ],
    "alcohol": ["alcohol", "alcoholic"],
    "war": [
        "war",
        "military",
        "troop",
        "ceasefire",
        "soldier",
        "air strike",
        "drone attack",
        "invasion",
        "hamas",
    ],
    "crime": [
        "crime",
        "criminal",
        "riot",
        "stabbed",
        "stabbing",
        "murder",
        "manslaughter",
        "killed",
        "killing",
        "gun",
        "bomb",
        "explosive",
        "jailed",
        "justice",
        "theft",
        "robbery",
        "looting",
        "police",
        "acquitted",
        "convicted",
        "hostage",
        "kidnap",
        "sexual assault",
        "sexual abuse",
        "child abuse",
        "illegal",
        "terrorist attack",
        "gardaí",
    ],
}

"""Words to have a hashtag applied if found in text"""
hashtags = [
    "Ireland",
    "Irish",
    "Carlow",
    "Cavan",
    "Clare",
    "Cork",
    "Donegal",
    "Dublin",
    "Galway",
    "Kerry",
    "Kildare",
    "Kilkenny",
    "Laois",
    "Leitrim",
    "Limerick",
    "Longford",
    "Louth",
    "Mayo",
    "Meath",
    "Monaghan",
    "Offaly",
    "Roscommon",
    "Sligo",
    "Tipperary",
    "Waterford",
    "Westmeath",
    "Wexford",
    "Wicklow",
    "Antrim",
    "Down",
    "Derry",
    "Armagh",
    "Tyrone",
    "Fermanagh",
    "Taoiseach",
    "Tánaiste",
]
